name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive_prefix: 'linux'
          - os: macos-latest
            target: x86_64-apple-darwin
            archive_prefix: 'macos'
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive_prefix: 'windows'

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build binaries (Release)
      run: |
        cargo build --release --all-features --all-targets --target ${{ matrix.target }}

    - name: Package binaries
      run: |
        mkdir -p package/bin
        cp target/${{ matrix.target }}/release/check-integrity package/bin/
        cp target/${{ matrix.target }}/release/find-duplicate package/bin/
        cp target/${{ matrix.target }}/release/hash-computer package/bin/
        cp README.md package/
        cp LICENSE package/
        cd package
        tar -czvf ../${{ matrix.archive_prefix }}-release.tar.gz .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.archive_prefix }}-release
        path: ${{ matrix.archive_prefix }}-release.tar.gz

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3

    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        path: *-release

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        files: |
          *-release/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
